version: "3.7"

services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - springboot-mysql-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://172.22.0.2:3306/humburguer?verifyServerCertificate=false&useSSL=false&requireSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3307:3306
    networks:
      - springboot-mysql-net
    environment:
      MYSQL_DATABASE: humburguer
      MYSQL_ROOT_PASSWORD: root
    container_name: mysqldb

networks:
  springboot-mysql-net:
