apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.configmap.name }}
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-svc:3306/humburguer"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_DATASOURCE_INITIALIZATION_MODE: "always"